CONFIGS_DIR="${${(%):-%x}:A:h:h}"

ZSH=$HOME/.oh-my-zsh
ZSH_THEME="af-magic"

# Must precede oh-my-zsh: its brew plugin picks up Intel brew in /usr/local otherwise
if [[ "$OSTYPE" == darwin* && -x /opt/homebrew/bin/brew ]]; then
  eval "$(/opt/homebrew/bin/brew shellenv zsh)"
fi

plugins=(git brew extract virtualenv rust zsh-completions)
if [[ "$OSTYPE" == darwin* ]]; then
  plugins+=(macos)
fi

source $ZSH/oh-my-zsh.sh

PATH=~/bin:$PATH
export PATH

source "$CONFIGS_DIR/bash/dir_colors.sh"

if (( $+commands[gls] )); then
  alias ls='gls --color=auto'
elif [[ "$OSTYPE" == darwin* ]]; then
  alias ls='ls -G'
else
  alias ls='ls --color=auto'
fi
alias l='ls -CF'
alias la='ls -A'
alias ll='ls -alhF'

# Debian/Ubuntu package fd as fdfind
if (( ! $+commands[fd] && $+commands[fdfind] )); then
  alias fd=fdfind
fi

DISABLE_UPDATE_PROMPT=true

autoload -U compinit && compinit

source "$CONFIGS_DIR/zsh/plugins/cmake-workflow/cmake-workflow.plugin.zsh"
